version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zend
      MYSQL_USER: zend
      MYSQL_PASSWORD: zend

  nginx:
    build: .
    image: nginx-zend
    restart: always
    ports:
      - "8081:80"

  zend:
    image: php-zendserver
    ports:
      - "8082:10081"
    restart: always
    depends_on:
      - nginx
      - db
volumes:
  db_data:


